image: rscohn2/oneapi-spec:latest

build:
  script:
  - python3 -m venv venv
  - . venv/bin/activate
  - pip install --quiet -r requirements.txt
  - python doc.py html
  - python doc.py latexpdf
  - python doc.py spelling

pages:
  only:
  - master
  script:
  - cp -r build/html public
  artifacts:
    paths:
    - public
